[package]
name = "jq-clone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.197"
serde_json = { version = "1.0.115", features = ["preserve_order"] }
winnow = "0.6.6"
